# Generated by Django 2.2.1 on 2019-08-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_posts',
            name='pdf',
            field=models.FileField(upload_to='posts/pdfs/'),
        ),
    ]
