# Generated by Django 2.2.1 on 2019-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0002_auto_20190822_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_posts',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
