# Generated by Django 2.2.1 on 2019-08-25 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0004_it_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_posts',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
