# Generated by Django 2.2.1 on 2019-08-25 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0005_auto_20190825_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_posts',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime.now),
        ),
    ]
