# Generated by Django 2.2.1 on 2019-08-25 12:16

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0006_auto_20190825_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_posts',
            name='postby',
            field=models.TextField(default=123, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
