# Generated by Django 2.2.1 on 2019-08-25 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0008_auto_20190825_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_posts',
            name='postby',
            field=models.ForeignKey(default=1, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
