# Generated by Django 2.2.1 on 2019-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0009_auto_20190825_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_posts',
            name='postby',
            field=models.TextField(max_length=20),
        ),
    ]
