# Generated by Django 2.2.1 on 2019-08-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0010_auto_20190825_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='it_posts',
            old_name='postby',
            new_name='posted',
        ),
    ]
