# Generated by Django 2.2.1 on 2019-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0011_auto_20190825_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_posts',
            name='posted',
            field=models.CharField(max_length=20),
        ),
    ]
