# Generated by Django 2.2.1 on 2019-08-25 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micit', '0013_auto_20190825_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_posts',
            name='posted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
